### ISSUE TITLE
Available on NPM or other?

### ISSUE THREAD

**Issue by ChrisSargent** [apioo/typeschema#11]
Hi, this looks very interesting but do you have the generators available as npm packages (or other non-node code) for programmatic usage?

Thanks!

Chris

**Comment by chriskapp** [comment]
Hi Chris, thanks for the feedback, yes so our generators are written in PHP an you could use them programmatically, therefor you need to checkout via composer the https://github.com/apioo/psx-schema library. This is basically the reference implemntation of TypeSchema but it would be also easy possible to build a generator in a different language.

**Comment by ChrisSargent** [comment]
Okay thanks!
