### ISSUE TITLE
Typeschema as a JSON Schema vocabulary

### ISSUE THREAD

**Issue by jdesrosiers** [apioo/typeschema#9]
Are you familiar with the concept of vocabularies in JSON Schema? We can't design JSON Schema for every use case, so we've limited our scope to validation and created the concept of vocabularies so others can tackle other problems for things like code generation, form building, etc.

Typeschema is exactly the kind thing vocabularies were created for, so it's exciting to see a project like this. The syntax is mostly JSON Schema already, so it would likely be as easy as adding a few lines to your meta-schema to declare your vocabulary. Vocabularies are still a very new concept, but in theory, defining a JSON Schema vocabulary for typeschema should help your adoption by allowing implementers to build off of standard JSON Schema tooling. For example, I could relatively easily implement typeschema using [Hyperjump JSC](https://github.com/hyperjump-io/json-schema-core) without having to rebuild all the parts that are shared with JSON Schema.

If you're interested, we'd be happy to help.

You can learn more about vocabularies in the JSON Schema Core specification, https://tools.ietf.org/html/draft-bhutton-json-schema-00

**Comment by gregsdennis** [comment]
I'd be keen to implement such a vocab for [JsonSchema.Net](https://github.com/gregsdennis/json-everything)!

**Comment by chriskapp** [comment]
Hi @jdesrosiers, thanks for the info. Yes, for some time we have already tried to create a JSON Schema vocabulary but we came to the conclusion that this does not fit well since TypeSchema thinks fundamentally different then JSON Schema about a schema. I.e. at TypeSchema we don't use JSON Path i.e. inside "$ref" you only reference a type by its name under the "definitions" key, there are no nested objects allowed, we have no "Keyword Independence" basically we have specific types which can use specific keywords but you cant mix them. Then we have also an explicit "$import" keyword to reference external documents. I have not deeply dived into the current core schema but from my understanding of the old JSON Schema days these are some core principles of JSON Schema. We have also wrote a post about our thoughts and the current situation, please take a look at:
https://chriskapp.medium.com/discussion-about-json-payloads-and-code-generation-8d60bc8fd94e

So sorry this is probably not the response your where looking for but we honestly think that this is technically the best way to proceed. Specifications are of course always political and every user has its own agenda. Currently we like to evolve the specification on its own and see how it goes but in general we are always open to find the best technical solution.

**Comment by jdesrosiers** [comment]
Hi Christoph,

I can tell you've made up your mind, so I won't push you. But you took the time to write up your thoughts and you deserve a response.

> TypeSchema thinks fundamentally different then JSON Schema about a schema.

Agreed. But, that doesn't rule out defining a JSON Schema vocabulary. It just means it won't be compatible with the JSON Schema validation vocabularies. Compatibility with validation would be ideal, but it's not required for a vocabulary.

> all vocabularies inherent properties from JSON Schema which are not suited for code generation.

I'm not sure, but there might be a slight misunderstanding here. The only thing that is required to be inherited from JSON Schema is the core vocabulary. That's things like `$schema`, `$id`, `$anchor`, `$ref`. The only thing in your vocab that wouldn't be compatible is your changes to how `$ref` works. You could get around that by giving it a different name such as `$definitionRef` and using your meta-schema to forbid the original `$ref` keyword.

Other than that, you can do just about anything you want. You can even have keywords with the same names as JSON Schema keywords but have different semantics.

> at TypeSchema we don't use JSON Path

Actually we use JSON Pointer, not JSON Path. That's not really relevant, but I thought you'd want to know to avoid confusion in future discussions.

> we have no "Keyword Independence" basically we have specific types which can use specific keywords but you cant mix them

That's not exactly what we mean by keyword independence. Keyword independence means that one keyword can't alter the behavior of another keyword. However, despite my protests, we break this rule frequently and allow vocabularies to break this rule.

> In JsonSchema we have the problem that we can evaluate a schema only in combination with the actual data, since we can combine multiple types and keywords and the keywords are applied based on the provided data.

You can enforce that every schema has one and only one type using the meta-schema. This is an extra constraint, but it's completely compatible with JSON Schema.

> we have also an explicit "$import" keyword to reference external documents

Not a problem. You can define any new keywords you need.

> there are no nested objects allowed

Again, this is perfectly compatible with JSON Schema and can be enforced using the meta-schema.

However, disallowing nested objects is only necessary because objects are named by `definitions`. If you allow schemas to declare their own name, this problem goes away. You could follow your current pattern of repurposing JSON Schema keywords and use "title", or you could create a new keyword like "name". You could even use the meta-schema to enforce that all object schemas have a "title".

> Generics

There's no with problem defining a `$template` keyword in a JSON Schema vocabulary. However, you might be interested to know that in draft 2020-12 we just added `$dynamicRef` which can be used for generics as well.

> In TypeSchema we see the “oneOf” and “allOf” keyword as union and intersection types

That would be problematic if interoperability with JSON Schema validation was desired, but it's not, so it's not a problem.

> In TypeSchema we have tried hard to not come up with many new keywords

As someone who helps the community with their schemas regularly, I would encourage you to rethink this approach. You've diverged significantly from JSON Schema, but use the same keywords. I can only see this causing confusion. Since interoperability with JSON Schema validation is clearly not a goal, why not select keyword names more appropriate for code generation? For example, `allOf` could be `union` and `oneOf` could be `intersection`.

---

To wrap up, if you want to, you could define TypeSchema as a JSON Schema vocabulary with only one small change. Vocabularies were designed to be very accommodating. However, given the degree to which you've diverged from JSON Schema, the value you get from defining a vocabulary would be relatively low. There's nothing wrong with the design choices you've made, but I personally think you can get just as clean of a design without losing interoperability with JSON Schema validation. I obviously haven't thought about this domain as deeply as you have, but let me know if you're interested in the thoughts I have about doing code generation without losing validation compatibility, otherwise I'll leave you alone. Good luck to you.
